### ISSUE TITLE
not working with Minimize on Close

### ISSUE THREAD

**Issue by ardi69** [farahats9/simple-startup-minimizer#1]
the plugin is not working is Minimize on Close activated

**Comment by farahats9** [comment]
I am not sure why but when I test with Minimize on Close it works for me, can you send more information like your OS and the log from thunderbird console?

**Comment by farahats9** [comment]
This should be fixed now in v0.5

**Comment by ardi69** [comment]
v0.5 works perfect for me. Thanx
