### ISSUE TITLE
Dont work anymore with TB 91.0.1

### ISSUE THREAD

**Issue by MisterT87** [farahats9/simple-startup-minimizer#3]
Hey Guys :) 
first of all: Thanks for this addon !

I am using Simple Startup Minimizer v0.5 and TB 91.0.1.
TB is starting auto with Windows (no delay) and TB window wont be minimized after autostart.

Have a nice day ! :)

**Comment by farahats9** [comment]
Thank you for reporting this, can you provide some context like what other addons you are using and if there are any errors in the error console (ctrl + shift + j)

**Comment by MisterT87** [comment]
No other addons running - just simple startup minimizer

Console Output: [pastebin.com](https://pastebin.com/gRtRsrFS)
console output captured after TB autostart.

**Comment by farahats9** [comment]
I just published the newest version after merging PR #2 so check the v0.6 and let me know if the issue still occurs

**Comment by MisterT87** [comment]
@farahats9 I will test this asap - gimme max 15 mins ;)

**Comment by MisterT87** [comment]
@farahats9 tested 4 times -> working like a charm now 👍

Question: Installed xpi file from this repo - if lets say simple startup minimizer v0.7 comes out from official thunderbird addons....
Do you know thunderbird client will auto update the manual installed version to newest (from thunderbird addon source) ?

Can be closed after answering question :)

**Comment by farahats9** [comment]
Glad it worked!
I am not sure if it will update or not but I just released the update on the thunderbird addons site and you can install it from there to make sure updates work (make sure you restart thunderbird after installing because sometimes it doesn't save the addons installed)
