### ISSUE TITLE
Startup minimizer isn't working anymore

### ISSUE THREAD

**Issue by arie051267** [farahats9/simple-startup-minimizer#4]
Hello,

When I start TB, TB isn't minimized at startup anymore.

Version TB is 91.0.2 and Startup-Minimizer is 0.6

I don't see any problems in the console (Ctrl+Shift+j)

Any idea what's the problem?

Kind regards,

Arie

**Comment by farahats9** [comment]
Make sure you disable all other addons, then restart TB and see if its minimized on start. If that works then some other addon is interfering with the addon and you need to enable them one by one and repeat restarting to find out which one is causing the problem.

**Comment by arie051267** [comment]
Tnx for the quick reply.
I have disabled all the other addons restart TB and I saw the TB icon again in the taskbar.
But when I go with my mouse over the TB again, the icon disappears ....

**Comment by farahats9** [comment]
Yes, I believe this is TB problem on windows but I could be wrong. TB is still running even if the icon disappears, it is advised you disable the "move to tray when minimized" option from the preferences.

**Comment by arie051267** [comment]
Correct, it looks like TB is still running. I have disabled this option in TB, it loooks like it's going OK now

**Comment by farahats9** [comment]
That's great, any idea which addon was causing the conflict?

**Comment by arie051267** [comment]
Nope, I don't think it was another addon causing the conflict.

I have added the TB to my taskbar and disabled in TB the option "move to tray when minimized"

**Comment by farahats9** [comment]
Ok thank you for the feedback.
