### ISSUE TITLE
System Tray icon dissappears at startup

### ISSUE THREAD

**Issue by Elaborendum** [farahats9/simple-startup-minimizer#5]
- SSM: v0.6
- OS: Win10
- Thunderbird 91.0.3

For some reason, when the addon is activated, Thunderbird opens, momentarily flashes as it gets minimized and appears in the system tray, only to disappear after a few seconds. Even if I open it and manually minimize it, it will not appear in the system tray, but it's still running anyway according to the task manager.

**Comment by farahats9** [comment]
this is a known issue on thunderbird, the recommended solution is to disable "minimize to tray" option in TB settings. I don't think it can be solved from the addon's side.

**Comment by krystian3w** [comment]
Maybe mozilla add API to disable option before close browser/mail window and enable after detect startup.

Few addons now can force enable containers or first-party isolation.

**Comment by farahats9** [comment]
Looks like recent TB update fixed this issue (tested with version 91.2.1)
Marking issue as closed now.
